blacklist regex env var instead of list of urls in file
odia/juscaba pull request #36
Opened 2021-11-08 18:30 UTC by seppo0010

2021-11-08 21:08 UTC, xaiki requested changes
It'd be great to pr against gh-actions branch so we can make sure it actually does what we want.

2021-11-08 21:08 UTC, xaiki commented on builder/main.go
> +	blacklist := os.Getenv("BLACKLIST_REGEX")
This mixes env vars and args to pass arguments.
We should choose one and stick towit.

2021-11-12 10:20 UTC, seppo0010 commented
Warning! The base is gh-actions and not main.

2021-11-12 13:01 UTC, xaiki requested changes
this is missing the actions part.

2021-11-12 13:01 UTC, xaiki commented on builder/extracttext/lib.go
> +	cmd := exec.Command("pdftohtml", "-c", p)
looks unrelated

2021-11-12 13:02 UTC, xaiki commented
commit history looks like it needs a cleanup.

2021-11-12 14:07 UTC, seppo0010 commented on builder/extracttext/lib.go
> +	cmd := exec.Command("pdftohtml", "-c", p)
you noticed

2021-11-12 14:07 UTC, seppo0010 commented
What do you mean? https://github.com/odia/juscaba/pull/36#pullrequestreview-804779024

2021-11-12 16:09 UTC, xaiki commented
i saw many commits, dunno why.

2021-11-12 16:09 UTC, merged